name: Build Apps

on:
  workflow_dispatch:
    inputs:
      build_api:
        type: boolean
        default: true
      build_frontend:
        type: boolean
        default: true
      build_admin:
        type: boolean
        default: true

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          services=()
          if [ "${{ github.event.inputs.build_api }}" = "true" ]; then services+=("api"); fi
          if [ "${{ github.event.inputs.build_frontend }}" = "true" ]; then services+=("frontend"); fi
          if [ "${{ github.event.inputs.build_admin }}" = "true" ]; then services+=("admin"); fi

          json=$(jq -nc --argjson arr "$(printf '%s\n' "${services[@]}" | jq -R . | jq -s .)" '{service:$arr}')
          echo "matrix=$json" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building ${{ matrix.service }}"

      - name: Build but only if admin
        if: matrix.service == 'admin'
        run: echo "Building admin aaaa"
  
  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.event.inputs.build_frontend == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4